<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQIxcBQq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQIxcBQq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQIxcBQq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQIxcBQq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQIxcBQq\App_KernelDevDebugContainer([
    'container.build_hash' => 'QIxcBQq',
    'container.build_id' => 'c782d5de',
    'container.build_time' => 1587564223,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQIxcBQq');
